spring:
  # H2 설정
  application.name: hexagonal
  datasource:
    h2:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false  # H2에서 Flyway 비활성화

  jackson:
    default-property-inclusion: non_null